name: heyo
description: Heyo messeging application
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  sembast: ^3.4.3+1
  http: ^0.13.4
  path_provider_android: ^2.0.15
  path_provider_ios: ^2.0.10
  flutter_webrtc: ^0.9.45
  sdp_transform: ^0.3.2
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  qr_flutter: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  flutter_screenutil: ^5.8.4
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.4.0
  emoji_picker_flutter: ^1.3.0
  flutter_keyboard_visibility: ^5.3.0
  intl: ^0.18.0
  # extended_image: ^8.0.2

  mobile_scanner: ^2.0.0
  share_plus: ^4.0.8
  image_editor: ^1.0.2
  # flutter_camera:
  #   git:
  #     url: git@ssh.git.energy:heyo/flutter_camera
  #     ref: development
  #
  photo_manager: ^2.7.1
  mime: ^1.0.2
  chewie: ^1.3.3
  just_audio: ^0.9.24
  record: ^4.1.1
  emojis: ^0.9.9
  connectivity_plus: ^2.3.4
  flutter_secure_storage: ^5.0.2
  convert: ^3.0.2
  pointycastle: ^3.6.0
  flutter_p2p_communicator:
    git:
      url: git@ssh.git.energy:corepass/flutter_p2p_communicator.git
      ref: 28d6bc8a

  flutter_bip39:
    git:
      url: git@ssh.git.energy:corepass/flutter_bip39.git

  flutter_osm_plugin: ^0.60.5
  permission_handler: ^10.0.0
  geolocator: ^9.0.2
  swipeable_tile: ^2.0.0
  expandable_bottom_sheet: ^1.1.1+1
  reorderables: ^0.5.0
  file_picker: ^5.0.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  ed_screen_recorder: ^0.0.10
  pull_to_refresh: ^2.0.0

  photo_view: ^0.14.0
  gallery_saver: ^2.3.2
  flutter_ringtone_player: ^3.2.0
  flutter_beep: ^1.0.0
  wakelock: ^0.6.2
  flutter_draggable_gridview: ^0.0.7
  crypto: ^3.0.2
  encrypt: ^5.0.1
  uuid: ^3.0.6
  tuple: ^2.0.1
  visibility_detector: ^0.3.3
  shimmer: ^2.0.0
  shared_preferences: ^2.1.0
  heyo_wifi_direct:
    git:
      url: git@ssh.git.energy:heyo/heyo_wifi_direct.git
  awesome_notifications: ^0.8.2
  url_launcher: 6.1.10
  uni_links: ^0.5.1
  flutter_native_splash: ^2.2.19
  flutter_slidable: ^3.0.0
  sentry_flutter: ^7.12.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.2.3+1
  freezed: ^2.4.3
  json_serializable: ^6.7.1

  core_flutter_lint:
    git: git@ssh.git.energy:corepass/core_flutter_lint.git
  core_web3dart:
    git:
      url: git@ssh.git.energy:corepass/core-web3dart.git
      ref: core-master

  flutter_launcher_icons: ^0.13.1

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/icon.png"

flutter_native_splash:
  image: "assets/png/splash.png"
  color: "#FFFFFF"
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  #android_12:
  #  image: "assets/png/heyo_logo.png"
  #  icon_background_color: "#02AEA4"

  web: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
