name: heyo
version: 1.0.0+1
publish_to: none
description: Heyo messeging application
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  core_flutter_lint: 
    git: git@git.energy:corepass/core_flutter_lint.git
  core_web3dart:
    git:
      url: git@git.energy:mojtabaparvar/core-web3dart.git
  flutter_bip39:
    git:
      url: git@git.energy:corepass/flutter_bip39.git

flutter: 
  uses-material-design: true

