name: heyo
description: Heyo messeging application
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  shimmer_animation: ^2.1.0+1
  flutter_screenutil: ^5.3.1
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.4.0
  connectivity_plus: ^2.3.0
  flutter_secure_storage: ^5.0.2
  convert: ^3.0.1
  pointycastle: ^3.2.0
  web3dart:
    git:
      url: git@git.energy:corepass/web3-dart-ethereum.git
  flutter_p2p_communicator:
    git:
      url: git@git.energy:corepass/flutter_p2p_communicator.git
  flutter_bip39:
    git:
      url: git@git.energy:corepass/flutter_bip39.git



dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  core_flutter_lint:
    git: git@git.energy:corepass/core_flutter_lint.git
  core_web3dart:
    git:
      url: git@git.energy:mojtabaparvar/core-web3dart.git

  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.1.1

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/icon.png"

flutter_native_splash:
  background_image: "assets/png/splash.png"
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
