name: heyo
description: Heyo messeging application
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  get: ^4.6.5
  qr_flutter: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  shimmer_animation: ^2.1.0+1
  flutter_screenutil: ^5.5.3+2
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.4.0
  emoji_picker_flutter: ^1.2.1
  flutter_keyboard_visibility: ^5.2.0
  intl: ^0.17.0
  extended_image: ^6.2.1
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.4
  chewie: ^1.3.3
  scroll_to_index: ^3.0.1
  just_audio: ^0.9.21
  record: ^4.1.1
  emojis: ^0.9.9
  connectivity_plus: ^2.3.0
  flutter_secure_storage: ^5.0.2
  convert: ^3.0.1
  pointycastle: ^3.6.0
  web3dart:
    git:
      url: git@git.energy:corepass/web3-dart-ethereum.git
  flutter_p2p_communicator:
    git:
      url: git@git.energy:corepass/flutter_p2p_communicator.git
  flutter_bip39:
    git:
      url: git@git.energy:corepass/flutter_bip39.git


  flutter_osm_plugin: ^0.34.0+1
  permission_handler: ^9.2.0
  osm_nominatim: ^2.0.1
  geolocator: ^8.2.1
  swipeable_tile: ^2.0.0
  expandable_bottom_sheet: ^1.1.1+1
  reorderables: ^0.5.0

dependency_overrides:
  permission_handler: ^9.2.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  core_flutter_lint:
    git: git@git.energy:corepass/core_flutter_lint.git
  core_web3dart:
    git:
      url: git@git.energy:mojtabaparvar/core-web3dart.git

  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.2.1

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/icon.png"

flutter_native_splash:
  background_image: "assets/png/splash.png"
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
