
import 'dart:convert';

import 'package:core_web3dart/crypto.dart';
import 'package:flutter/foundation.dart';

class WEB3CLIENT {
  static const url = 'https://xcbapi.corecoin.cc';

  static const username = '';

  static const password = '';

}

const String ID_CARD_PRE_FIX_IN_SC = 'IDCARD';
const String PASSPORT_PRE_FIX_IN_SC = 'PASSPORT';
const String RESIDENCE_PERMIT_PRE_FIX_IN_SC = 'RESIDENCE_PERMIT';
const String DRIVER_LICENSE_PRE_FIX_IN_SC = 'DRIVER_LICENSE';
const String ADDRESS_PRE_FIX_IN_SC = 'ADDRESS';
const String EMAIL_PRE_FIX_IN_SC = 'EMAIL';
const String PHONE_PRE_FIX_IN_SC = 'PHONE';

enum MINTABLE_FIELDS {
  IDCARD_NAME,
  IDCARD_NAME_EN,
  IDCARD_DOB,
  IDCARD_EXPIRY_DATE,
  IDCARD_ISSUE_DATE,
  IDCARD_DOCUMENT_NUMBER,
  IDCARD_SEX,
  IDCARD_COUNTRY,
  IDCARD_DOCUMENT_IMAGE,
  IDCARD_FACE_IMAGE,
  IDCARD_ADDITIONAL_IMAGE,
  IDCARD_AML_CHECK,
  IDCARD_AML_DETAIL,
  PASSPORT_NAME,
  PASSPORT_NAME_EN,
  PASSPORT_DOB,
  PASSPORT_EXPIRY_DATE,
  PASSPORT_ISSUE_DATE,
  PASSPORT_DOCUMENT_NUMBER,
  PASSPORT_SEX,
  PASSPORT_COUNTRY,
  PASSPORT_DOCUMENT_IMAGE,
  PASSPORT_FACE_IMAGE,
  PASSPORT_ADDITIONAL_IMAGE,
  PASSPORT_AML_CHECK,
  PASSPORT_AML_DETAIL,
  RESIDENCE_PERMIT_NAME,
  RESIDENCE_PERMIT_NAME_EN,
  RESIDENCE_PERMIT_DOB,
  RESIDENCE_PERMIT_EXPIRY_DATE,
  RESIDENCE_PERMIT_ISSUE_DATE,
  RESIDENCE_PERMIT_DOCUMENT_NUMBER,
  RESIDENCE_PERMIT_SEX,
  RESIDENCE_PERMIT_COUNTRY,
  RESIDENCE_PERMIT_DOCUMENT_IMAGE,
  RESIDENCE_PERMIT_FACE_IMAGE,
  RESIDENCE_PERMIT_ADDITIONAL_IMAGE,
  RESIDENCE_PERMIT_AML_CHECK,
  RESIDENCE_PERMIT_AML_DETAIL,
  DRIVER_LICENSE_NAME,
  DRIVER_LICENSE_NAME_EN,
  DRIVER_LICENSE_DOB,
  DRIVER_LICENSE_EXPIRY_DATE,
  DRIVER_LICENSE_ISSUE_DATE,
  DRIVER_LICENSE_DOCUMENT_NUMBER,
  DRIVER_LICENSE_SEX,
  DRIVER_LICENSE_COUNTRY,
  DRIVER_LICENSE_DOCUMENT_IMAGE,
  DRIVER_LICENSE_FACE_IMAGE,
  DRIVER_LICENSE_ADDITIONAL_IMAGE,
  DRIVER_LICENSE_AML_CHECK,
  DRIVER_LICENSE_AML_DETAIL,
  ADDRESS_NAME,
  ADDRESS_NAME_EN,
  ADDRESS_ISSUE_DATE,
  ADDRESS_EXPIRY_DATE,
  ADDRESS_STREET,
  ADDRESS_STREET2,
  ADDRESS_DIVISION,
  ADDRESS_CITY,
  ADDRESS_ZIP_CODE,
  ADDRESS_COUNTRY,
  ADDRESS_DOCUMENT_IMAGE,
  ADDRESS_STREET_EN,
  ADDRESS_STREET2_EN,
  ADDRESS_DIVISION_EN,
  ADDRESS_CITY_EN,
  EMAIL,
  PHONE
}

final Map<MINTABLE_FIELDS, String> mintableFieldsNameHashMapping = {
  MINTABLE_FIELDS.IDCARD_NAME: '${ID_CARD_PRE_FIX_IN_SC}_NAME',
  MINTABLE_FIELDS.IDCARD_NAME_EN: '${ID_CARD_PRE_FIX_IN_SC}_NAME_EN',
  MINTABLE_FIELDS.IDCARD_DOB: '${ID_CARD_PRE_FIX_IN_SC}_DOB',
  MINTABLE_FIELDS.IDCARD_EXPIRY_DATE: '${ID_CARD_PRE_FIX_IN_SC}_EXPIRY_DATE',
  MINTABLE_FIELDS.IDCARD_ISSUE_DATE: '${ID_CARD_PRE_FIX_IN_SC}_ISSUE_DATE',
  MINTABLE_FIELDS.IDCARD_DOCUMENT_NUMBER:
  '${ID_CARD_PRE_FIX_IN_SC}_DOCUMENT_NUMBER',
  MINTABLE_FIELDS.IDCARD_SEX: '${ID_CARD_PRE_FIX_IN_SC}_SEX',
  MINTABLE_FIELDS.IDCARD_COUNTRY: '${ID_CARD_PRE_FIX_IN_SC}_COUNTRY',
  MINTABLE_FIELDS.IDCARD_DOCUMENT_IMAGE:
  '${ID_CARD_PRE_FIX_IN_SC}_DOCUMENT_IMAGE',
  MINTABLE_FIELDS.IDCARD_FACE_IMAGE: '${ID_CARD_PRE_FIX_IN_SC}_FACE_IMAGE',
  MINTABLE_FIELDS.IDCARD_ADDITIONAL_IMAGE:
  '${ID_CARD_PRE_FIX_IN_SC}_ADDITIONAL_IMAGE',
  MINTABLE_FIELDS.IDCARD_AML_CHECK: '${ID_CARD_PRE_FIX_IN_SC}_AML_CHECK',
  MINTABLE_FIELDS.IDCARD_AML_DETAIL: '${ID_CARD_PRE_FIX_IN_SC}_AML_DETAIL',
  MINTABLE_FIELDS.PASSPORT_NAME: '${PASSPORT_PRE_FIX_IN_SC}_NAME',
  MINTABLE_FIELDS.PASSPORT_NAME_EN: '${PASSPORT_PRE_FIX_IN_SC}_NAME_EN',
  MINTABLE_FIELDS.PASSPORT_DOB: '${PASSPORT_PRE_FIX_IN_SC}_DOB',
  MINTABLE_FIELDS.PASSPORT_EXPIRY_DATE: '${PASSPORT_PRE_FIX_IN_SC}_EXPIRY_DATE',
  MINTABLE_FIELDS.PASSPORT_ISSUE_DATE: '${PASSPORT_PRE_FIX_IN_SC}_ISSUE_DATE',
  MINTABLE_FIELDS.PASSPORT_DOCUMENT_NUMBER:
  '${PASSPORT_PRE_FIX_IN_SC}_DOCUMENT_NUMBER',
  MINTABLE_FIELDS.PASSPORT_SEX: '${PASSPORT_PRE_FIX_IN_SC}_SEX',
  MINTABLE_FIELDS.PASSPORT_COUNTRY: '${PASSPORT_PRE_FIX_IN_SC}_COUNTRY',
  MINTABLE_FIELDS.PASSPORT_DOCUMENT_IMAGE:
  '${PASSPORT_PRE_FIX_IN_SC}_DOCUMENT_IMAGE',
  MINTABLE_FIELDS.PASSPORT_FACE_IMAGE: '${PASSPORT_PRE_FIX_IN_SC}_FACE_IMAGE',
  MINTABLE_FIELDS.PASSPORT_ADDITIONAL_IMAGE:
  '${PASSPORT_PRE_FIX_IN_SC}_ADDITIONAL_IMAGE',
  MINTABLE_FIELDS.PASSPORT_AML_CHECK: '${PASSPORT_PRE_FIX_IN_SC}_AML_CHECK',
  MINTABLE_FIELDS.PASSPORT_AML_DETAIL: '${PASSPORT_PRE_FIX_IN_SC}_AML_DETAIL',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_NAME:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_NAME',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_NAME_EN:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_NAME_EN',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_DOB: '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_DOB',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_EXPIRY_DATE:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_EXPIRY_DATE',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_ISSUE_DATE:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_ISSUE_DATE',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_DOCUMENT_NUMBER:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_DOCUMENT_NUMBER',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_SEX: '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_SEX',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_COUNTRY:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_COUNTRY',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_DOCUMENT_IMAGE:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_DOCUMENT_IMAGE',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_FACE_IMAGE:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_FACE_IMAGE',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_ADDITIONAL_IMAGE:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_ADDITIONAL_IMAGE',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_AML_CHECK:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_AML_CHECK',
  MINTABLE_FIELDS.RESIDENCE_PERMIT_AML_DETAIL:
  '${RESIDENCE_PERMIT_PRE_FIX_IN_SC}_AML_DETAIL',
  MINTABLE_FIELDS.DRIVER_LICENSE_NAME: '${DRIVER_LICENSE_PRE_FIX_IN_SC}_NAME',
  MINTABLE_FIELDS.DRIVER_LICENSE_NAME_EN:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_NAME_EN',
  MINTABLE_FIELDS.DRIVER_LICENSE_DOB: '${DRIVER_LICENSE_PRE_FIX_IN_SC}_DOB',
  MINTABLE_FIELDS.DRIVER_LICENSE_EXPIRY_DATE:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_EXPIRY_DATE',
  MINTABLE_FIELDS.DRIVER_LICENSE_ISSUE_DATE:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_ISSUE_DATE',
  MINTABLE_FIELDS.DRIVER_LICENSE_DOCUMENT_NUMBER:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_DOCUMENT_NUMBER',
  MINTABLE_FIELDS.DRIVER_LICENSE_SEX: '${DRIVER_LICENSE_PRE_FIX_IN_SC}_SEX',
  MINTABLE_FIELDS.DRIVER_LICENSE_COUNTRY:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_COUNTRY',
  MINTABLE_FIELDS.DRIVER_LICENSE_DOCUMENT_IMAGE:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_DOCUMENT_IMAGE',
  MINTABLE_FIELDS.DRIVER_LICENSE_FACE_IMAGE:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_FACE_IMAGE',
  MINTABLE_FIELDS.DRIVER_LICENSE_ADDITIONAL_IMAGE:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_ADDITIONAL_IMAGE',
  MINTABLE_FIELDS.DRIVER_LICENSE_AML_CHECK:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_AML_CHECK',
  MINTABLE_FIELDS.DRIVER_LICENSE_AML_DETAIL:
  '${DRIVER_LICENSE_PRE_FIX_IN_SC}_AML_DETAIL',
  MINTABLE_FIELDS.ADDRESS_NAME: '${ADDRESS_PRE_FIX_IN_SC}_NAME',
  MINTABLE_FIELDS.ADDRESS_NAME_EN: '${ADDRESS_PRE_FIX_IN_SC}_NAME_EN',
  MINTABLE_FIELDS.ADDRESS_ISSUE_DATE: '${ADDRESS_PRE_FIX_IN_SC}_ISSUE_DATE',
  MINTABLE_FIELDS.ADDRESS_EXPIRY_DATE: '${ADDRESS_PRE_FIX_IN_SC}_EXPIRY_DATE',
  MINTABLE_FIELDS.ADDRESS_STREET: '${ADDRESS_PRE_FIX_IN_SC}_STREET',
  MINTABLE_FIELDS.ADDRESS_STREET2: '${ADDRESS_PRE_FIX_IN_SC}_STREET2',
  MINTABLE_FIELDS.ADDRESS_DIVISION: '${ADDRESS_PRE_FIX_IN_SC}_DIVISION',
  MINTABLE_FIELDS.ADDRESS_CITY: '${ADDRESS_PRE_FIX_IN_SC}_CITY',
  MINTABLE_FIELDS.ADDRESS_ZIP_CODE: '${ADDRESS_PRE_FIX_IN_SC}_ZIP_CODE',
  MINTABLE_FIELDS.ADDRESS_COUNTRY: '${ADDRESS_PRE_FIX_IN_SC}_COUNTRY',
  MINTABLE_FIELDS.ADDRESS_DOCUMENT_IMAGE:
  '${ADDRESS_PRE_FIX_IN_SC}_DOCUMENT_IMAGE',
  MINTABLE_FIELDS.ADDRESS_STREET_EN: '${ADDRESS_PRE_FIX_IN_SC}_STREET_EN',
  MINTABLE_FIELDS.ADDRESS_STREET2_EN: '${ADDRESS_PRE_FIX_IN_SC}_STREET2_EN',
  MINTABLE_FIELDS.ADDRESS_DIVISION_EN: '${ADDRESS_PRE_FIX_IN_SC}_DIVISION_EN',
  MINTABLE_FIELDS.ADDRESS_CITY_EN: '${ADDRESS_PRE_FIX_IN_SC}_CITY_EN',
  MINTABLE_FIELDS.EMAIL: EMAIL_PRE_FIX_IN_SC,
  MINTABLE_FIELDS.PHONE: PHONE_PRE_FIX_IN_SC
};


Uint8List getSha3ForNames(MINTABLE_FIELDS name) {
  return sha3_256(Uint8List.fromList(
      utf8.encode(mintableFieldsNameHashMapping[name] ?? '')));
}
